# Default values for test-prom.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana: 
  adminPassword: unitest123
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: 'Default'
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      blackbox:
        gnetId: 13659
        datasource: Prometheus
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://test1-prometheus-server

prometheus:
  extraScrapeConfigs: |
    - job_name: 'prometheus-blackbox-exporter'
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
          - https://google.com
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: test1-prometheus-blackbox-exporter:9115           


prometheus-blackbox-exporter:
  modules:
        http_2xx:
          http:
            no_follow_redirects: false
            preferred_ip_protocol: ip4
            valid_http_versions:
            - HTTP/1.1
            - HTTP/2
            valid_status_codes: []
          prober: http
          timeout: 5s
